sonar.projectKey=xbenja105_infernal-rise
sonar.organization=xbenja105
sonar.host.url=https://sonarcloud.io
sonar.token=be75057baa7e958287dddaa92a0422db3599a9b3
sonar.sources=js,index.html,styles.css
sonar.exclusions=**/node_modules/**,**/assets/**
sonar.sourceEncoding=UTF-8
